version: "3"

services:
  auth_service:
    build:
      context: ./auth-service
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    volumes:
      - ./auth-service:/app
    networks:
      - backend

  product_service:
    build:
      context: ./product-service
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    volumes:
      - ./product-service:/app
    networks:
      - backend

  frontend:
    build:
      context: ./frontend-app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4200
    ports:
      - "4200:80"
    depends_on:
      - auth_service
      - product_service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    networks:
      - backend

networks:
  backend:
    driver: bridge
